### ISSUE TITLE
Consider latexmk over pdflatex

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#18]
latexmk automatically runs the correct number of times (which is not always twice) and can intelligently clean up after itself. However, I don't know whether it is installed by default on the major TeX distributions (TeX Live, MiKTeX, MacTeX).

It reduces this:

```
cap rm "`using1'.pdf"
*run pdflatex twice for hyperref
!pdflatex "`using1'.tex" & pdflatex "`using1'.tex"
*erase aux files
cap rm "`using1'.log"
cap rm "`using1'.aux"
cap rm "`using1'.lot"
cap rm "`using1'.out"
cap rm "`using1'.ttt"
```

to this:

```
!latexmk -pdf "`using1'.tex" && latexmk -c
```

**Comment by NilsEnevoldsen** [comment]
Correction: latexmk will not remove .ttt files by default. It can be configured to do so by specifying `-e 'push @generated_exts, "ttt";'`. The .ttt file is used by endfloat, I think.

Hence:

```
!latexmk -pdf "`using1'.tex" && latexmk -e 'push @generated_exts, "ttt";' -c
```

**Comment by derekwolfson** [comment]
I think I'm against this change unless we can be certain that most people have latexmk.  I only worry about the double compilation for hyperref so the list command can work.  

I'm not certain compiling it the "right" amount of times is important here since the functionality of tex3pt is just to create a .pdf of the results.
