### ISSUE TITLE
Is there an advantage to \specialcell over \shortstack?

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#3]
tex3pt encourages the use of a user-defined command, `\specialcell`.

```
% Allow line breaks with \\ in specialcells
\newcommand{\specialcell}[2][c]{%
    \begin{tabular}[#1]{@{}c@{}}#2\end{tabular}
}
```

Does `\specialcell` have any advantage over `\shortstack`?

**Comment by derekwolfson** [comment]
I'll answer this question with two related comments!

First, I borrowed this code from Jorg Weber (http://www.jwe.cc/), so I'm not sure if he coded /specialcell specifically to deal with the (perhaps non-existent) shortcomings of \shortstack

Second, I'm not familiar with \shortstack, but my intuition tells me that if it work well within a tabular environment, then it should be fine.

If this is the case, I'll write in the helpfile that one can use either the specially coded \specialcell syntax or the \shortstack syntax and provide a link to some documentation on \shortstack. 

I'm reluctant to remove the definition of \specialcell from the preamble since it would break any .do files which rely on the \specialcell syntax.

I'll play around with \shortstack next time I use tex3pt for Stata output.  Perhaps it is the better way forward.  Please let me know if it works for you - I'm all for using built-ins over user-defined commands.

**Comment by NilsEnevoldsen** [comment]
Yes, I agree that removing the code from the preamble would not be good. I was thinking about changing the help file, if it turned out that `\specialcell` were not needed. Using a built-in command makes code more portable, reduces confusion, etc. I'll reach out to Jorg.

**Comment by derekwolfson** [comment]
Very well. Thanks for the continued input.

-D

Typed with two thumbs.

**Comment by joergweber** [comment]
The point of \specialcell is to provide a manual breaking point of a cell, specifically for column headers. estauto and esttab provide no facility for this, hence the need for it. 

If I am not mistaken, the difference to \specialcell is that the content of the "cell" is always centered, which would not be the case with \shortstack. In any case, I've borrowed the solution from here: http://tex.stackexchange.com/a/19678/11984

**Comment by NilsEnevoldsen** [comment]
If I'm understanding correctly, current behavior is this:

| Command | Horizontal alignment | Vertical alignment |
| --- | --- | --- |
| `\specialcell` | `c` (others possible if command is modified) | `t`, `b`, `c` (default) |
| `\shortstack` | `r`, `l`, `c` (default) | `b` (not even an option per se) |

We can't mess with the `\specialcell` implementation and be backwards compatible. It seems to me that the most common use case is for table headers, in which case the proper alignment is usually (always?) horizontally center aligned and vertically bottom aligned. I just checked a few journals around me, and they all format table headers this way.

It seems to me that `\shortstack` has the proper behavior by default, and `\specialcell` can be coerced to proper behavior with the `b` option.

It remains possible that `\shortstack` has undesirable behavior in some environment which I haven't yet encountered. It has been working well for me for a few months.

I guess my preference at this point would be to quietly retire `\specialcell` from the documentation, and recommend `\shortstack`.
