### ISSUE TITLE
Significance stars protrude outside table

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#8]
Significance stars protrude outside the right edge of the table. This is especially apparent with triple stars.

Maybe related to this hack in the preamble:

```
\newcommand{\sym}[1]{\rlap{#1}}
```

For reference: [Jörg's TeX Exchange question](http://tex.stackexchange.com/questions/47418/siunitx-specifying-custom-command-as-input-symbol), to which this hack was provided as an answer.

**Comment by NilsEnevoldsen** [comment]
They can also protrude into other columns. I have output that resembles this:

```
     short looooooong_dep_var
var1 3.45***    5.234*
           ^
          Ugly
```

**Comment by derekwolfson** [comment]
I typically fix this by specifying a sufficient value for cwidth.

**Comment by derekwolfson** [comment]
tex3pt in its current build writes something like:

```
\estauto{"test11.tex"}{4}{S[table-format=1.3] S[table-format=2.3]}
```

where

```
S[table-format=X.Y]
```

means there are a maximum of X digits before the decimal point and a maximum of Y digits after the decimal point.  Each of these are column specific.

The way to fix this so that the stars don't bleed into the next column is to change this to account for the space necessary for the stars.  Let's assume that there are three stars max in the first column, and two stars max in the second column.  In this case, the correct code that'll fix this spillage is:

```
\estauto{"test11.tex"}{4}{S[table-format=1.3,table-space-text-post=***] S[table-format=2.3,table-space-text-post=**]
```

Now, I need to revisit how I extract X & Y, so I can also extract the number of stars (or other symbols in the future) and write them into the table code.  The table code is going to get pretty large and nasty looking, but it'll make a pretty table without having to specify c-widths.
