### ISSUE TITLE
Some notes are being gobbled

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#9]
When I write

```
note( ///
    "Note 1." ///
    "Note 2." ///
)
```

I sometimes see

```
\Figtext{{\footnotesize Note 1.}} %%TABLE NOTE
\Figtext{{\footnotesize }} %%TABLE NOTE
```

This will probably take some additional troubleshooting. It's not actually entirely clear how that input should be interpreted. The help file says that "To force a line break in the notes insert a comma between notes.  For example, note("note1", "note2") will insert note1 on one line and note2 on a separate line." I have no comma, but I get a line break regardless. I expected no line break.

**Comment by NilsEnevoldsen** [comment]
The empty note appears to be due to the final `/// )`.

Including commas after every line does cause every note to show up. I am puzzled why some of my notes in this format appear to display even when not preceded by a comma.

**Comment by derekwolfson** [comment]
There is all sorts of weird stuff going on here.

In a few different scenarios I get the behavior you mention

```
note("Note 1." "Note 2.")
```

gives

```
\Figtext{{\footnotesize Note 1.}} %%TABLE NOTE
\Figtext{{\footnotesize }} %%TABLE NOTE
```

```
note( ///
"This is a note in tex3pt!", ///
"THIS IS ALSO A NOTE!" ///
) 
```

gives 

```
\Figtext{{\footnotesize This is a note in tex3pt!}} %%TABLE NOTE
\Figtext{{\footnotesize THIS IS ALSO A NOTE!}} %%TABLE NOTE
\Figtext{{\footnotesize }} %%TABLE NOTE
```

So you are right that the `/// )` is causing issues, but something else is troublesome here.

First, I need to figure out why it is creating a blank line.  The code that processes the notes is below:

```

        **BREAK NOTE INTO LINES**
            local notelines = 0
            if `"`note'"'!=""{
            local ++notelines
            gettoken part rest: note, parse(",")
            local note`notelines' `"`part'"'

             while `"`rest'"'!="" {
              local ++notelines 
              gettoken part rest: rest, parse(",")
              gettoken part rest: rest, parse(",")
              local note`notelines' `"`part'"'
             }
            }
```

It is almost surely due to the `gettoken` call.  This shouldn't be too hard to fiddle with.  

Second, I (we) need to think about the best way to process notes.  I like the idea that you should be able to type multiple notes in quotations directly into the tex3pt command with `///` line delimiters, like:

```
note( ///
    "Note 1. " ///
    "Note 2." ///
)
```

and get 

```
\Figtext{{\footnotesize Note 1. Note2.}} %%TABLE NOTE
```

in the .tex file.  

I originally wanted to make that that separate sets of text set off in quotations would be on different lines, but this makes it impossible to use the `///` delimiters in Stata to spread your longer notes across lines.  I never noticed this problem because I circumvent the problem entirely by storing my notes in locals like this: 

```
local NOTE "Part one of really long note."
local NOTE "`NOTE' Part two of really long note."
```

But due to individual tastes, people may not like this.  I usually control the text in each of my LaTeX tables with locals  like `TITLE` and `LABEL` that I can plug directly into the tex3pt command.

I'll troubleshoot this behavior a bit when I get some free time.  I think it makes sense to have the `,` outside the quotations lead to line breaks, so I will keep that, or at least similar, functionality.

**Comment by NilsEnevoldsen** [comment]
Just to confirm, the behavior you describe is the behavior I both expect and prefer.

You're a champ at responding to these issues, by the way. I'm partly just jotting them down for my own sanity, and here you come waltzing in fixing all of them. :open_mouth:

**Comment by NilsEnevoldsen** [comment]
Fixed by 170b417, but should be tested first.

**Comment by NilsEnevoldsen** [comment]
Did you test this? It worked for me, but it seems ripe for breaking. Commas in notes, weird white space, stuff like that.

**Comment by derekwolfson** [comment]
I’m working with it now – I like the fix, but I think you may be correct that it may fix one thing and break a few others.

**Comment by NilsEnevoldsen** [comment]
Did you file issues for the things that broke?

edit: Oh, you're not sure if it broke anything.
